name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Docker image
      run: docker build -t registry.digitalocean.com/hale-container-registry/hale-be:latest .

    - name: Login to DigitalOcean Container Registry
      run: echo ${{ secrets.DOCKER_ACCESS_TOKEN }} | docker login registry.digitalocean.com -u anggaraputra9552@gmail.com --password-stdin

    - name: Push Docker image to DigitalOcean Container Registry
      run: docker push registry.digitalocean.com/hale-container-registry/hale-be:latest

    - name: Deploy to DigitalOcean Droplet
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} root@137.184.73.216 << 'EOF'
          docker pull registry.digitalocean.com/hale-container-registry/hale-be:latest
          docker stop hale-be-container || true
          docker rm hale-be-container || true
          docker run -d --name hale-be-container -p 3000:3000 -e MONGO_URI=${{ secrets.MONGO_URI }} registry.digitalocean.com/hale-container-registry/hale-be:latest
        EOF
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        NODE_ENV: ${{ secrets.NODE_ENV }}
        PORT: ${{ secrets.PORT }}

